[package]
name = "write_to"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
write_to_derive = { path = "write_to_derive" }
bit-vec = "0.6.2"